//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionPregunta
    {
        public int PreguntaId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public Nullable<int> TipoCarreraId { get; set; }
        public Nullable<int> ClaveOpcionId { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Pregunta Pregunta { get; set; }
        public virtual TipoCarrera TipoCarrera { get; set; }
    }
}
