//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDocentes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public int EncuestaId { get; set; }
        public Nullable<int> ConfiguracionEncuestaId { get; set; }
        public Nullable<int> PreguntaId { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModifico { get; set; }
    
        public virtual ConfiguracionEncuesta ConfiguracionEncuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
