//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDocentes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IESEEntities : DbContext
    {
        public IESEEntities()
            : base("name=IESEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoMateria> AlumnoMateria { get; set; }
        public virtual DbSet<AlumnoPrueba> AlumnoPrueba { get; set; }
        public virtual DbSet<AlumnoPruebaServicio> AlumnoPruebaServicio { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<ComentarioDocente> ComentarioDocente { get; set; }
        public virtual DbSet<ComentarioServicios> ComentarioServicios { get; set; }
        public virtual DbSet<ConfiguracionEncuesta> ConfiguracionEncuesta { get; set; }
        public virtual DbSet<ConfiguracionPregunta> ConfiguracionPregunta { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<DocenteMateria> DocenteMateria { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<HistorialAlumno> HistorialAlumno { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<OpcionPregunta> OpcionPregunta { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<PreguntaDocente> PreguntaDocente { get; set; }
        public virtual DbSet<PreguntaServicios> PreguntaServicios { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<TipoCarrera> TipoCarrera { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
